# Generated by Django 3.1.2 on 2020-10-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed_que',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=150)),
                ('admin_id', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('BBA', 'BBA'), ('MBA', 'MBA')], max_length=150)),
                ('subject_name', models.CharField(max_length=150)),
                ('semester', models.CharField(max_length=150)),
            ],
        ),
    ]
