# Generated by Django 3.1.2 on 2020-10-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_db',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subject_db',
            name='subject_code',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='feed_que',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
