# Generated by Django 3.1.2 on 2020-10-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201028_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_data_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True)),
                ('contact', models.CharField(max_length=150)),
            ],
        ),
    ]
