# Generated by Django 3.1.2 on 2020-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_student_data_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data_db',
            name='sems',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
