# Generated by Django 3.1.2 on 2020-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_student_data_db_sems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data_db',
            old_name='sems',
            new_name='course',
        ),
        migrations.AddField(
            model_name='student_data_db',
            name='enrollment_no',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student_data_db',
            name='password',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_data_db',
            name='sem_start',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_data_db',
            name='contact',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='student_data_db',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
