# Generated by Django 3.1.2 on 2020-10-29 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20201029_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data_db',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
