# Generated by Django 3.1.2 on 2020-10-29 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_student_data_db_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data_db',
            name='created_at',
        ),
        migrations.AddField(
            model_name='student_data_db',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
