# Generated by Django 3.1.2 on 2020-10-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20201029_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data_db',
            name='sem',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
