# Generated by Django 3.1.2 on 2020-11-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_student_data_db_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data_db',
            name='password',
            field=models.CharField(default='rhany', max_length=150),
        ),
    ]
