# Generated by Django 3.1.2 on 2020-11-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20201101_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50, unique=True)),
                ('adminid', models.CharField(max_length=150)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=150)),
                ('subject_code', models.CharField(max_length=150)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50, unique=True)),
                ('studentid', models.CharField(max_length=150)),
                ('enrollment_no', models.CharField(max_length=150)),
                ('student_rating', models.CharField(max_length=150)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject_db',
            name='semester',
        ),
        migrations.AlterField(
            model_name='student_data_db',
            name='password',
            field=models.CharField(default='ezqrb', max_length=150),
        ),
        migrations.AlterField(
            model_name='subject_db',
            name='course_name',
            field=models.CharField(choices=[('BCA-sem-1', 'BCA-sem-1'), ('BCA-sem-2', 'BCA-sem-2'), ('BCA-sem-3', 'BCA-sem-3'), ('BCA-sem-4', 'BCA-sem-4'), ('BCA-sem-5', 'BCA-sem-5'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BBA', 'BBA'), ('MBA', 'MBA')], max_length=150),
        ),
    ]
