# Generated by Django 3.1.2 on 2020-11-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20201102_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data_db',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
