# Generated by Django 3.1.2 on 2020-11-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20201102_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_db',
            name='course_name',
            field=models.CharField(choices=[('BCA-sem-1', 'BCA-sem-1'), ('BCA-sem-2', 'BCA-sem-2'), ('BCA-sem-3', 'BCA-sem-3'), ('BCA-sem-4', 'BCA-sem-4'), ('BCA-sem-5', 'BCA-sem-5'), ('BCA-sem-6', 'BCA-sem-6'), ('MCA-sem-3', 'MCA-sem-3'), ('MCA-sem-4', 'MCA-sem-4'), ('MCA-sem-5', 'MCA-sem-5'), ('MCA-sem-6', 'MCA-sem-6'), ('BBA-sem-1', 'BBA-sem-1'), ('BBA-sem-2', 'BBA-sem-2'), ('BBA-sem-3', 'BBA-sem-3'), ('BBA-sem-4', 'BBA-sem-4'), ('BBA-sem-5', 'BBA-sem-5'), ('BBA-sem-6', 'BBA-sem-6'), ('MBA-sem-3', 'MBA-sem-3'), ('MBA-sem-4', 'MBA-sem-4'), ('MBA-sem-5', 'MBA-sem-5'), ('MBA-sem-6', 'MBA-sem-6')], max_length=150),
        ),
    ]
